FROM rust:1.59 as builder
WORKDIR /usr/src/bda
COPY . .
RUN cargo install --path bdacli

FROM debian:11.3-slim
COPY --from=builder /usr/local/cargo/bin/bdacli /usr/local/bin/bdacli
CMD ["bdadatastore"]